---

- name: Calculate OJS install paths
  set_fact:
    ojs_calculated_paths:
       "{{ ojs_calculated_paths|default([]) + [ ojs_parent_dir + '/' + item.0.name +'/sites/' + item.1.path] }}"
  with_subelements:
    - "{{ ojs_sites }}"
    - installs
  tags: always 


- debug:
    msg: "{{ ojs_calculated_paths }}"
  tags: always  

- include: deploy.yml
  become: true
  tags: ojs_deploy
  with_items: "{{ ojs_calculated_paths|default([]) }}" 

- include: plugins.yml
  become: true
  tags: ojs_crossref
  with_items: "{{ ojs_calculated_paths|default([]) }}"

- include: upgrade.yml
  become: true
  tags: ojs_upgrade
  with_items: "{{ ojs_calculated_paths|default([]) }}"

#- include: search.yml
#  become: true
#  tags: ojs_search
